Spender/Controllers/PaymentModeController.cs
using Spender.Models;
using Spender.Repository;
using Spender.ViewModels;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;
using AutoMapper;

namespace Spender.Controllers
{
    public class PaymentModeController : Controller
    {
        private IPaymentModeRepository paymentModeRepository;

        public PaymentModeController(IPaymentModeRepository paymentModeRepository)
        {
            this.paymentModeRepository = paymentModeRepository;
        }

        [Route("PaymentMode/Index")]
        public ActionResult Index()
        {
            var vm = new PaymentModeIndex();
            vm.PageTitle = "Payment Mode";
            vm.PaymentMode = new PaymentModeViewModel();
            return View(vm);
        }

        [Route("PaymentMode/List")]
        public ActionResult List()
        {
            IEnumerable<PaymentModeViewModel> vm = Mapper.Map<IEnumerable<PaymentModeViewModel>>(this.paymentModeRepository.Get());
            return PartialView(vm);
        }

        [Route("PaymentMode/Edit")]
        [HttpGet]
        public ActionResult Edit(int paymentModeId)
        {
            var paymentMode = this.paymentModeRepository.GetById(paymentModeId);
            var model = Mapper.Map<PaymentModeViewModel>(paymentMode);
            return PartialView("Edit", model);
        }

        [Route("PaymentMode/Edit")]
        [HttpPost]
        public ActionResult Edit(PaymentModeViewModel model)
        {
            PaymentMode paymentMode = Mapper.Map<PaymentMode>(model);
            this.paymentModeRepository.Save(paymentMode);
            return RedirectToAction("Index");
        }
    }
}

Spender/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <base href="/spender" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")    
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/application/angular")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body ng-app="spenderApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Payment Mode","Index","PaymentMode")</li>
                    <li><a href="/spender/category">Category</a></li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>                
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>